services:
  fuseki:
    image: secoresearch/fuseki:5.2.0
    user: "1000"
    container_name: fuseki
    ports:
      - "3030:3030"
    environment:
      - ADMIN_PASSWORD=admin
      - ENABLE_DATA_WRITE=true
      - ENABLE_UPDATE=true
      - ENABLE_SHACL=false
      - QUERY_TIMEOUT=60000
    volumes:
      - ./fuseki-data:/fuseki-base/databases
    restart: "no"
