services:
  fuseki:
    image: secoresearch/fuseki:5.2.0
    user: "1000"
    container_name: fuseki
    ports:
      - "3030:3030"
    environment:
      - ADMIN_PASSWORD=admin
      - ENABLE_DATA_WRITE=true
      - ENABLE_UPDATE=true
      - ENABLE_SHACL=false
      - QUERY_TIMEOUT=60000
    volumes:
      - ./fuseki-data:/fuseki-base/databases
    restart: "no"
  minio:
    image: bitnami/minio:2024.12.18
    user: "1000"
    container_name: minio
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./minio-data:/bitnami/minio/data
    restart: "no"
