# Copyright © 2024-2025 CRS4
# Copyright © 2025 BSC
#
# This file is part of ProvStor.
#
# ProvStor is free software: you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# ProvStor is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with ProvStor. If not, see <https://www.gnu.org/licenses/>.


services:
  fuseki:
    image: secoresearch/fuseki:5.2.0
    user: "1000"
    container_name: fuseki
    ports:
      - "3030:3030"
    environment:
      - ADMIN_PASSWORD=${FUSEKI_ADMIN_PASSWORD}
      - ENABLE_DATA_WRITE=${ENABLE_DATA_WRITE}
      - ENABLE_UPDATE=${ENABLE_UPDATE}
      - ENABLE_SHACL=${ENABLE_SHACL}
      - QUERY_TIMEOUT=${QUERY_TIMEOUT}
    volumes:
      - fuseki-data:/fuseki-base/databases
    restart: "no"

  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=${MINIO_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET}
    volumes:
      - minio-data:/data
    restart: "no"

  api:
    image: provstor-api:1.0
    build:
      context: .
      dockerfile: api.Dockerfile
    container_name: provstor-api
    ports:
      - 8000:8000
    environment:
      - FUSEKI_BASE_URL=${FUSEKI_BASE_URL}
      - FUSEKI_DATASET=${FUSEKI_DATASET}
      - MINIO_STORE=${MINIO_STORE}
      - MINIO_USER=${MINIO_USER}
      - MINIO_SECRET=${MINIO_SECRET}
      - MINIO_BUCKET=${MINIO_BUCKET}
    depends_on:
      - fuseki
      - minio
    restart: "no"
    pull_policy: never

volumes:
  fuseki-data:
  minio-data:
