# Copyright © 2024-2026 CRS4
# Copyright © 2025-2026 BSC
#
# This file is part of ProvStor.
#
# ProvStor is free software: you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# ProvStor is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with ProvStor. If not, see <https://www.gnu.org/licenses/>.


services:
  fuseki:
    image: secoresearch/fuseki:5.5.0
    user: "1000"
    container_name: fuseki
    ports:
      - "3030:3030"
    environment:
      - ADMIN_PASSWORD=${FUSEKI_ADMIN_PASSWORD}
      - ENABLE_DATA_WRITE=${ENABLE_DATA_WRITE}
      - ENABLE_UPDATE=${ENABLE_UPDATE}
      - ENABLE_SHACL=${ENABLE_SHACL}
      - QUERY_TIMEOUT=${QUERY_TIMEOUT}
    volumes:
      - fuseki-data:/fuseki-base/databases
    restart: "no"

  seaweedfs-s3:
    image: chrislusf/seaweedfs:4.17
    container_name: seaweedfs-s3
    ports:
      - "8333:8333"
      - "8888:8888"
    entrypoint: /bin/sh -c
    command: |
      "echo '{
        \"identities\": [
          {
            \"name\": \"anonymous\",
            \"actions\": [
              \"Read\"
            ]
          },
          {
            \"name\": \"${SEAWEEDFS_USER}\",
            \"credentials\": [
              {
                \"accessKey\": \"${SEAWEEDFS_ACCESS_KEY}\",
                \"secretKey\": \"${SEAWEEDFS_SECRET_KEY}\"
              }
            ],
            \"actions\": [
              \"Admin\",
              \"Read\",
              \"List\",
              \"Tagging\",
              \"Write\"
            ]
          }
        ]
      }' > /etc/seaweedfs/config.json && \
      weed server -dir /s3data -s3 -s3.config /etc/seaweedfs/config.json -filer"
    volumes:
      - seaweedfs-data:/s3data
    restart: no

  api:
    image: provstor-api:1.1
    user: "1000"
    build:
      context: .
      dockerfile: api.Dockerfile
    container_name: provstor-api
    ports:
      - 8000:8000
    environment:
      - FUSEKI_BASE_URL=${FUSEKI_BASE_URL}
      - FUSEKI_DATASET=${FUSEKI_DATASET}
      - SEAWEEDFS_STORE=${SEAWEEDFS_STORE}
      - SEAWEEDFS_FILER=${SEAWEEDFS_FILER}
      - SEAWEEDFS_USER=${SEAWEEDFS_USER}
      - SEAWEEDFS_ACCESS_KEY=${SEAWEEDFS_ACCESS_KEY}
      - SEAWEEDFS_SECRET_KEY=${SEAWEEDFS_SECRET_KEY}
      - SEAWEEDFS_BUCKET=${SEAWEEDFS_BUCKET}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
    depends_on:
      - fuseki
      - seaweedfs-s3
    restart: "no"
    pull_policy: never

volumes:
  fuseki-data:
  seaweedfs-data:
